"""Simple client wrapper for requesting patches from an LLM endpoint."""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Dict, Optional

import requests


@dataclass
class PatchSuggestion:
    diff: str
    summary: str


class ModelClient:
    """Send condensed error reports and code to a language model service."""

    def __init__(self, endpoint: Optional[str] = None, api_key: Optional[str] = None):
        self.endpoint = endpoint
        self.api_key = api_key

    def build_prompt(self, errors: str, code: str, path: str, context: str) -> str:
        return (
            "You are a PHP expert. Receive static analysis errors, the source file, "
            "and the described issue. Produce a minimal patch fixing the problems.\n\n"
            f"Target: {path}\nContext: {context}\n\n"
            "Errors:\n"
            f"{errors}\n\n"
            "Code:\n"
            f"{code}\n\n"
            "Respond with a unified diff or full corrected file, and a one-line summary."
        )

    def request_patch(self, errors: str, code: str, path: str, context: str) -> PatchSuggestion:
        prompt = self.build_prompt(errors, code, path, context)

        if not self.endpoint:
            # Offline-friendly fallback response.
            diff = (
                f"--- a/{path}\n"
                f"+++ b/{path}\n"
                "-// original code\n"
                "+// patched code placeholder based on static analysis.\n"
            )
            summary = "Generated placeholder patch suggestion."
            return PatchSuggestion(diff=diff, summary=summary)

        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        payload: Dict[str, Any] = {"prompt": prompt}
        response = requests.post(self.endpoint, headers=headers, data=json.dumps(payload), timeout=30)
        response.raise_for_status()
        data = response.json()

        diff = data.get("diff") or data.get("text") or ""
        summary = data.get("summary") or "Patch generated by model."
        return PatchSuggestion(diff=diff, summary=summary)
