"""Predefined genre and mood templates."""

GENRE_TEMPLATES = {
    "lofi": {
        "genre": "Lo-Fi",
        "mood": "chill",
        "tempo": 85,
        "scale": [220.0, 246.94, 277.18, 293.66, 329.63, 369.99, 415.3],
        "sections": ["intro", "verse", "chorus", "outro"],
        "keywords": ["study", "lofi", "relax", "coffee"],
        "instruments": [
            {
                "name": "lead",
                "waveform": "sine",
                "pattern": [0, 2, 4, 5],
                "rhythm": [1, 1, 1, 1],
                "volume": 0.45,
                "envelope": {"attack": 0.05, "release": 0.6},
            },
            {
                "name": "chords",
                "waveform": "triangle",
                "pattern": [0, 3, 4, 2],
                "rhythm": [2, 2, 2, 2],
                "volume": 0.35,
                "envelope": {"attack": 0.1, "release": 0.8},
            },
            {
                "name": "bass",
                "waveform": "square",
                "pattern": [0, 0, 5, 4],
                "rhythm": [2, 2, 2, 2],
                "volume": 0.3,
                "octave": -1,
                "envelope": {"attack": 0.02, "release": 0.3},
            },
            {
                "name": "drums",
                "waveform": "noise",
                "pattern": [None, None, None, None],
                "rhythm": [0.5, 0.5, 0.5, 0.5],
                "volume": 0.25,
                "envelope": {"attack": 0.005, "release": 0.12},
            },
        ],
    },
    "pop": {
        "genre": "Pop",
        "mood": "upbeat",
        "tempo": 120,
        "scale": [261.63, 293.66, 329.63, 349.23, 392.0, 440.0, 493.88],
        "sections": ["intro", "verse", "chorus", "bridge", "chorus"],
        "keywords": ["pop", "catchy", "radio"],
        "instruments": [
            {
                "name": "hook",
                "waveform": "saw",
                "pattern": [0, 2, 4, 5, 4, 2, 0, 2],
                "rhythm": [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
                "volume": 0.5,
                "envelope": {"attack": 0.02, "release": 0.3},
            },
            {
                "name": "chords",
                "waveform": "triangle",
                "pattern": [0, 3, 4, 5],
                "rhythm": [2, 2, 2, 2],
                "volume": 0.35,
                "envelope": {"attack": 0.05, "release": 0.5},
            },
            {
                "name": "bass",
                "waveform": "square",
                "pattern": [0, 0, 3, 4],
                "rhythm": [1, 1, 1, 1],
                "volume": 0.3,
                "octave": -1,
                "envelope": {"attack": 0.01, "release": 0.2},
            },
            {
                "name": "drums",
                "waveform": "noise",
                "pattern": [None, None, None, None],
                "rhythm": [0.5, 0.5, 0.5, 0.5],
                "volume": 0.28,
                "envelope": {"attack": 0.003, "release": 0.08},
            },
        ],
    },
    "cinematic": {
        "genre": "Cinematic",
        "mood": "epic",
        "tempo": 100,
        "scale": [174.61, 196.0, 220.0, 246.94, 277.18, 311.13, 349.23],
        "sections": ["intro", "build", "climax", "resolution"],
        "keywords": ["film", "orchestra", "cinematic"],
        "instruments": [
            {
                "name": "strings",
                "waveform": "saw",
                "pattern": [0, 3, 4, 5],
                "rhythm": [4, 4, 4, 4],
                "volume": 0.55,
                "envelope": {"attack": 0.1, "release": 1.2},
            },
            {
                "name": "horns",
                "waveform": "triangle",
                "pattern": [0, 4, 3, 5],
                "rhythm": [2, 2, 2, 2],
                "volume": 0.4,
                "envelope": {"attack": 0.05, "release": 0.8},
            },
            {
                "name": "percussion",
                "waveform": "noise",
                "pattern": [None, None, None, None],
                "rhythm": [0.5, 0.5, 0.5, 0.5],
                "volume": 0.22,
                "envelope": {"attack": 0.002, "release": 0.12},
            },
        ],
    },
    "edm": {
        "genre": "EDM",
        "mood": "energetic",
        "tempo": 128,
        "scale": [261.63, 293.66, 329.63, 391.0, 440.0, 523.25, 587.33],
        "sections": ["intro", "build", "drop", "breakdown"],
        "keywords": ["club", "dance", "edm"],
        "instruments": [
            {
                "name": "lead",
                "waveform": "saw",
                "pattern": [0, 2, 4, 7],
                "rhythm": [0.5, 0.5, 0.5, 0.5],
                "volume": 0.55,
                "envelope": {"attack": 0.01, "release": 0.2},
            },
            {
                "name": "plucks",
                "waveform": "square",
                "pattern": [0, 3, 5, 7],
                "rhythm": [0.25, 0.25, 0.25, 0.25],
                "volume": 0.3,
                "envelope": {"attack": 0.005, "release": 0.25},
            },
            {
                "name": "bass",
                "waveform": "square",
                "pattern": [0, 0, 3, 4],
                "rhythm": [0.5, 0.5, 0.5, 0.5],
                "volume": 0.4,
                "octave": -1,
                "envelope": {"attack": 0.002, "release": 0.15},
            },
            {
                "name": "drums",
                "waveform": "noise",
                "pattern": [None, None, None, None],
                "rhythm": [0.25, 0.25, 0.25, 0.25],
                "volume": 0.3,
                "envelope": {"attack": 0.001, "release": 0.08},
            },
        ],
    },
    "jazz": {
        "genre": "Jazz",
        "mood": "smooth",
        "tempo": 110,
        "scale": [261.63, 311.13, 349.23, 392.0, 466.16, 523.25, 587.33],
        "sections": ["intro", "theme", "solo", "theme"],
        "keywords": ["jazz", "sax", "swing"],
        "instruments": [
            {
                "name": "sax",
                "waveform": "sine",
                "pattern": [0, 2, 4, 5],
                "rhythm": [1, 1, 1, 1],
                "volume": 0.45,
                "envelope": {"attack": 0.03, "release": 0.4},
            },
            {
                "name": "comping",
                "waveform": "triangle",
                "pattern": [0, 3, 5, 2],
                "rhythm": [2, 2, 2, 2],
                "volume": 0.35,
                "envelope": {"attack": 0.05, "release": 0.6},
            },
            {
                "name": "walking-bass",
                "waveform": "square",
                "pattern": [0, 2, 4, 5],
                "rhythm": [1, 1, 1, 1],
                "volume": 0.32,
                "octave": -1,
                "envelope": {"attack": 0.02, "release": 0.3},
            },
            {
                "name": "brushes",
                "waveform": "noise",
                "pattern": [None, None, None, None],
                "rhythm": [0.5, 0.5, 0.5, 0.5],
                "volume": 0.22,
                "envelope": {"attack": 0.01, "release": 0.2},
            },
        ],
    },
    "ambient": {
        "genre": "Ambient",
        "mood": "dreamy",
        "tempo": 60,
        "scale": [110.0, 146.83, 196.0, 220.0, 261.63, 329.63, 392.0],
        "sections": ["drone", "texture", "swells", "release"],
        "keywords": ["ambient", "relax", "space"],
        "instruments": [
            {
                "name": "pads",
                "waveform": "sine",
                "pattern": [0, 3, 5, 2],
                "rhythm": [8, 8, 8, 8],
                "volume": 0.5,
                "envelope": {"attack": 0.5, "release": 1.5},
            },
            {
                "name": "textures",
                "waveform": "triangle",
                "pattern": [1, 4, 6, 3],
                "rhythm": [4, 4, 4, 4],
                "volume": 0.35,
                "envelope": {"attack": 0.4, "release": 1.2},
            },
            {
                "name": "sub",
                "waveform": "sine",
                "pattern": [0, 0, 0, 0],
                "rhythm": [4, 4, 4, 4],
                "volume": 0.25,
                "octave": -1,
                "envelope": {"attack": 0.3, "release": 1.0},
            },
        ],
    },
}
